GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3dhbWUiLCJpYXQiOjE2NjMzMjA0MDUsImV4cCI6MTY2MzMyMDQyMH0.hGg8ls0IvK_nKBTsnAJc2FYR3hjWX6B85SvZNQWKa2M

###

POST http://localhost:4001/login
Content-Type: application/json

{
    "username": "kwame"
}